# Intruduction to Numpy

## Importing Numpy

In [69]:
import numpy as np

## Creating arrays

In [70]:
# From Zeros 
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [71]:
# From Ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [72]:
# From a single value
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [73]:
# From an array
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [74]:
# From a range
# np.arrange(start, end)

np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [75]:
# From a linspace
# np.linspace(start, end, number_of_elements)

np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

## Multi-dementional Arrays

In [76]:
# np.zeros(shape=(rows, cols))
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [77]:
n = np.array([
    [1, 2, 4],
    [4, 5, 6],
    [7, 8, 9],
]
)
n

array([[1, 2, 4],
       [4, 5, 6],
       [7, 8, 9]])

## Randomly generated Arrays

In [78]:
# Using Uniform Distribution
np.random.rand(5, 2)

array([[0.07964548, 0.50524609],
       [0.0652865 , 0.42812233],
       [0.09653092, 0.12715997],
       [0.59674531, 0.226012  ],
       [0.10694568, 0.22030621]])

In [79]:
# For reproducebility 
# Fix a seed

np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [80]:
# Using Normal Distribution

np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [81]:
# Random Integer

np.random.randint(low=0, high=100, size=(5, 2))


array([[37, 39],
       [67,  4],
       [42, 51],
       [38, 33],
       [58, 67]], dtype=int32)

## Indexing Numpy Arrays

In [82]:
# One Dimentional array
a[2]
a

array([1, 2, 3, 4])

In [83]:
# Assinging new value
a[2] = 4
a

array([1, 2, 4, 4])

In [84]:
# One Dimentional array
# array[row, cols]

n[0, 1] = 20
n

array([[ 1, 20,  4],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [85]:
n[2] = [1, 1, 1]
n

array([[ 1, 20,  4],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [86]:
# Indexing cols
# ":"" means all elements

n[:, 2]
n

array([[ 1, 20,  4],
       [ 4,  5,  6],
       [ 1,  1,  1]])

## Element-wise operations

In [87]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [88]:
a + 1

array([1, 2, 3, 4, 5])

In [89]:
a * 2

array([0, 2, 4, 6, 8])

In [90]:
(10 + (a * 2)) / 5 * (a - 2)

array([-4. , -2.4,  0. ,  3.2,  7.2])

## Comaprison Operations

In [91]:
a > 2

array([False, False, False,  True,  True])

In [92]:
a[a > 2]

array([3, 4])

## Summerzing Operations

In [93]:
a.sum()

np.int64(10)

In [94]:
a.min()

np.int64(0)

In [95]:
n.std()

np.float64(5.6916659888291985)